name: CD

on: push

env:
  CI: true

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Set environment from cloudtruth
        uses: cloudtruth/configure-action@v2
        with:
          apikey: "${{ secrets.CLOUDTRUTH_API_KEY }}"
          project: "deploy"
          environment: "production"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t cloudtruth/templates:latest .

      - name: Push the Docker image
        run: |
          docker push cloudtruth/templates:latest
